//! End-to-end integration tests for Capa 3 expansion features

use std::fs;
use std::path::PathBuf;
use tempfile::TempDir;

/// Test scenario: Comprehensive multi-language project setup
#[test]
fn test_capa3_polyglot_project_detection() {
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let project_path = temp_dir.path();

    // Create a polyglot project with multiple languages
    fs::write(project_path.join("Cargo.toml"), "[package]\nname=\"test\"")
        .expect("Failed to create Cargo.toml");

    fs::write(project_path.join("pom.xml"), "<project></project>")
        .expect("Failed to create pom.xml");

    fs::write(project_path.join("package.json"), "{}")
        .expect("Failed to create package.json");

    fs::write(project_path.join("go.mod"), "module test")
        .expect("Failed to create go.mod");

    // Detect all languages
    let detected = sentinel_rust::config::SentinelConfig::detect_project_languages(project_path);

    // Verify all languages are detected
    assert!(detected.contains(&"rust".to_string()), "Should detect Rust");
    assert!(detected.contains(&"java".to_string()), "Should detect Java");
    assert!(
        detected.contains(&"typescript".to_string()),
        "Should detect TypeScript"
    );
    assert!(detected.contains(&"go".to_string()), "Should detect Go");
}

/// Test scenario: Custom rules in a project
#[test]
fn test_capa3_custom_rules_loading() {
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let project_path = temp_dir.path();

    // Create custom rules
    let rules_dir = project_path.join(".sentinel").join("custom-rules");
    fs::create_dir_all(&rules_dir).expect("Failed to create rules directory");

    let rule1 = r#"type: pattern
name: "No Debugger"
pattern: "debugger"
file_patterns: ["**/*.ts"]
severity: error
message: "Debugger statement not allowed"
enabled: true
"#;

    let rule2 = r#"type: pattern
name: "No Console"
pattern: "console\\.log"
file_patterns: ["**/*.ts"]
severity: warning
message: "Console output should be removed"
enabled: true
"#;

    fs::write(rules_dir.join("no_debugger.yaml"), rule1)
        .expect("Failed to write rule 1");
    fs::write(rules_dir.join("no_console.yaml"), rule2)
        .expect("Failed to write rule 2");

    // Initialize rule engine with custom rules
    let mut engine = sentinel_rust::rules::RuleEngine::new()
        .with_project_path(project_path);

    engine.load_custom_rules().expect("Failed to load custom rules");

    // Verify custom rules were loaded
    assert_eq!(
        engine.custom_rules.len(),
        2,
        "Should load both custom rules"
    );
}

/// Test scenario: Language detection and project setup
#[test]
fn test_capa3_detect_rust_and_java_projects() {
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let project_path = temp_dir.path();

    // Create Rust markers
    fs::write(project_path.join("Cargo.toml"), "[package]\n")
        .expect("Failed to create Cargo.toml");

    let src = project_path.join("src");
    fs::create_dir_all(&src).expect("Failed to create src");

    fs::write(src.join("main.rs"), "fn main() {}")
        .expect("Failed to create main.rs");

    // Verify Rust detection
    assert!(
        sentinel_rust::config::SentinelConfig::detect_rust_project(project_path),
        "Should detect Rust project"
    );

    // Create Java project in a subdirectory
    let java_subdir = project_path.join("java_module");
    fs::create_dir_all(&java_subdir).expect("Failed to create java_module");

    fs::write(
        java_subdir.join("pom.xml"),
        "<project></project>"
    )
    .expect("Failed to create pom.xml");

    // Verify Java detection in subdirectory
    assert!(
        sentinel_rust::config::SentinelConfig::detect_java_project(&java_subdir),
        "Should detect Java project in subdirectory"
    );
}

/// Test scenario: Pre-commit hook template content validation
#[test]
fn test_capa3_precommit_hook_template_complete() {
    let template = include_str!("../src/precommit_template.sh");

    // Verify all critical sections are present
    assert!(
        template.contains("#!/bin/bash"),
        "Should be a bash script"
    );
    assert!(
        template.contains("Pre-commit hook generated by Sentinel Pro"),
        "Should identify as Sentinel hook"
    );
    assert!(
        template.contains("Running Sentinel pre-commit checks"),
        "Should mention checking"
    );
    assert!(
        template.contains("git diff --cached"),
        "Should check staged files"
    );
    assert!(
        template.contains("sentinel pro"),
        "Should invoke sentinel commands"
    );
    assert!(
        template.contains("--no-verify"),
        "Should document how to bypass"
    );
}

/// Test scenario: GitHub Actions workflows are complete
#[test]
fn test_capa3_github_actions_workflows_complete() {
    let analysis = include_str!("../templates/sentinel-analysis.yml");
    let tests = include_str!("../templates/sentinel-tests.yml");
    let security = include_str!("../templates/sentinel-security.yml");

    // Analysis workflow
    assert!(analysis.contains("sentinel pro check"), "Should run check");
    assert!(
        analysis.contains("Comment PR with Results"),
        "Should comment on PRs"
    );

    // Tests workflow
    assert!(tests.contains("sentinel pro test-all"), "Should run tests");
    assert!(
        tests.contains("upload-artifact"),
        "Should upload test results"
    );

    // Security workflow
    assert!(security.contains("sentinel pro audit"), "Should run audit");
    assert!(
        security.contains("schedule:"),
        "Should have scheduled runs"
    );
    assert!(
        security.contains("upload-sarif"),
        "Should upload SARIF report"
    );
}

/// Test scenario: Tree-sitter language support
#[test]
fn test_capa3_language_parser_supports_java_rust() {
    // Test Java parsing
    let java_code = "public class Example { }";
    let mut java_parser = sentinel_rust::rules::language_support::LanguageParser::new(
        sentinel_rust::rules::language_support::SupportedLanguage::Java,
    )
    .expect("Failed to create Java parser");

    let java_tree = java_parser.parse(java_code).expect("Failed to parse Java");
    assert!(java_tree.root_node().child_count() > 0, "Should parse Java code");

    // Test Rust parsing
    let rust_code = "fn test() { }";
    let mut rust_parser = sentinel_rust::rules::language_support::LanguageParser::new(
        sentinel_rust::rules::language_support::SupportedLanguage::Rust,
    )
    .expect("Failed to create Rust parser");

    let rust_tree = rust_parser
        .parse(rust_code)
        .expect("Failed to parse Rust");
    assert!(rust_tree.root_node().child_count() > 0, "Should parse Rust code");
}

/// Test scenario: Custom rules execution in validation pipeline
#[test]
fn test_capa3_custom_rules_in_validation() {
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let project_path = temp_dir.path();

    // Create a custom rule
    let rules_dir = project_path.join(".sentinel").join("custom-rules");
    fs::create_dir_all(&rules_dir).expect("Failed to create rules directory");

    let rule = r#"type: pattern
name: "Test Pattern"
pattern: "FORBIDDEN"
file_patterns: ["**/*.txt"]
severity: error
message: "Found forbidden pattern"
enabled: true
"#;

    fs::write(rules_dir.join("test_rule.yaml"), rule)
        .expect("Failed to write rule");

    // Create rule engine and load custom rules
    let mut engine = sentinel_rust::rules::RuleEngine::new()
        .with_project_path(project_path);

    engine.load_custom_rules().expect("Failed to load custom rules");

    // Validate a file with the custom rule
    let test_file = PathBuf::from("test.txt");
    let content_with_violation = "This file contains FORBIDDEN pattern";
    let content_clean = "This file is clean";

    let violations_bad = engine.validate_file(&test_file, content_with_violation);
    let violations_good = engine.validate_file(&test_file, content_clean);

    assert!(
        violations_bad.iter().any(|v| v.rule_name == "Test Pattern"),
        "Should find custom rule violation"
    );
    assert!(
        !violations_good.iter().any(|v| v.rule_name == "Test Pattern"),
        "Should not find violation in clean code"
    );
}

/// Test scenario: Project structure detection for multiple languages
#[test]
fn test_capa3_mixed_language_project_structure() {
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let project_path = temp_dir.path();

    // Create a complex project structure with multiple languages at root level
    // Root level: Node.js
    fs::write(project_path.join("package.json"), "{}")
        .expect("Failed to write package.json");

    // Root: Rust (Cargo.toml at project root)
    fs::write(project_path.join("Cargo.toml"), "[package]\n")
        .expect("Failed to write Cargo.toml");

    // Root: Java (pom.xml at project root for Maven)
    fs::write(project_path.join("pom.xml"), "<project></project>")
        .expect("Failed to write pom.xml");

    // Root: Go
    fs::write(project_path.join("go.mod"), "module test\n")
        .expect("Failed to write go.mod");

    // Detect languages
    let detected = sentinel_rust::config::SentinelConfig::detect_project_languages(project_path);

    assert!(
        detected.contains(&"typescript".to_string()),
        "Should detect Node.js"
    );
    assert!(detected.contains(&"rust".to_string()), "Should detect Rust");
    assert!(detected.contains(&"java".to_string()), "Should detect Java");
    assert!(detected.contains(&"go".to_string()), "Should detect Go");
}

/// Test scenario: Capa 3 feature integration
#[test]
fn test_capa3_all_features_together() {
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let project_path = temp_dir.path();

    // Initialize git repository
    fs::create_dir_all(project_path.join(".git"))
        .expect("Failed to create .git");

    // Create a Rust project
    fs::write(project_path.join("Cargo.toml"), "[package]\nname=\"test\"\n")
        .expect("Failed to write Cargo.toml");

    let src = project_path.join("src");
    fs::create_dir_all(&src).expect("Failed to create src");
    fs::write(src.join("lib.rs"), "pub fn test() {}")
        .expect("Failed to write lib.rs");

    // Create custom rules
    let rules_dir = project_path.join(".sentinel").join("custom-rules");
    fs::create_dir_all(&rules_dir).expect("Failed to create rules dir");

    let rule = r#"type: pattern
name: "Integration Test Rule"
pattern: "test_pattern"
file_patterns: ["**/*.rs"]
severity: warning
message: "Found test pattern"
enabled: true
"#;

    fs::write(rules_dir.join("integration_test.yaml"), rule)
        .expect("Failed to write custom rule");

    // Verify Rust project detection
    assert!(
        sentinel_rust::config::SentinelConfig::detect_rust_project(project_path),
        "Should detect Rust project"
    );

    // Create and configure rule engine with custom rules
    let mut engine = sentinel_rust::rules::RuleEngine::new()
        .with_project_path(project_path);

    engine.load_custom_rules().expect("Failed to load custom rules");

    // Verify engine has custom rules
    assert!(
        !engine.custom_rules.is_empty(),
        "Should have loaded custom rules"
    );

    // Test validation
    let test_file = PathBuf::from("src/lib.rs");
    let _violations = engine.validate_file(&test_file, "pub fn test_pattern() {}");

    // Test passes if we can load and execute all components
    assert!(true, "All Capa 3 features integrated successfully");
}
