//! Integration tests for pre-commit hook functionality

use std::fs;
use tempfile::TempDir;

#[test]
fn test_precommit_template_exists() {
    // The template should be embedded in the binary
    let content = include_str!("../src/precommit_template.sh");
    assert!(!content.is_empty(), "Pre-commit template should not be empty");
}

#[test]
fn test_precommit_template_is_bash_script() {
    let content = include_str!("../src/precommit_template.sh");
    assert!(
        content.starts_with("#!/bin/bash"),
        "Template should be a bash script"
    );
}

#[test]
fn test_precommit_template_has_sentinel_marker() {
    let content = include_str!("../src/precommit_template.sh");
    assert!(
        content.contains("Pre-commit hook generated by Sentinel Pro"),
        "Template should identify itself as Sentinel-generated"
    );
}

#[test]
fn test_precommit_template_mentions_checks() {
    let content = include_str!("../src/precommit_template.sh");
    assert!(
        content.contains("Sentinel pre-commit checks"),
        "Template should mention running Sentinel checks"
    );
}

#[test]
fn test_precommit_template_checks_staged_files() {
    let content = include_str!("../src/precommit_template.sh");
    assert!(
        content.contains("git diff --cached"),
        "Template should check staged files with git"
    );
}

#[test]
fn test_precommit_template_exits_on_failure() {
    let content = include_str!("../src/precommit_template.sh");
    assert!(
        content.contains("exit 1") && content.contains("Pre-commit checks failed"),
        "Template should exit with error on failure"
    );
}

#[test]
fn test_precommit_template_has_file_check_logic() {
    let content = include_str!("../src/precommit_template.sh");
    assert!(
        content.contains("\\.(ts|tsx|js|jsx|rs|java|go|py)$"),
        "Template should check specific file extensions"
    );
}

#[test]
fn test_precommit_hook_install_structure() {
    // Test that the command structure is correct
    // We can't actually install without a real git repo, but we can verify the structure
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let project_path = temp_dir.path();

    // Initialize a git repository
    let git_dir = project_path.join(".git");
    fs::create_dir_all(&git_dir).expect("Failed to create .git directory");

    // The hook should be installable in this structure
    assert!(git_dir.exists(), "Git directory should exist for hook installation");
}

#[test]
fn test_precommit_bypass_message() {
    let content = include_str!("../src/precommit_template.sh");
    assert!(
        content.contains("--no-verify"),
        "Template should mention how to bypass the hook"
    );
}

#[test]
fn test_precommit_provides_meaningful_output() {
    let content = include_str!("../src/precommit_template.sh");
    assert!(
        content.contains("✅") || content.contains("✔"),
        "Template should provide meaningful success output"
    );
    assert!(
        content.contains("❌") || content.contains("✗"),
        "Template should provide meaningful failure output"
    );
}

#[test]
fn test_precommit_template_handles_empty_staged() {
    let content = include_str!("../src/precommit_template.sh");
    assert!(
        content.contains("if [ -z \"$STAGED_FILES\" ]"),
        "Template should handle case with no staged files"
    );
}

#[test]
fn test_precommit_template_gets_project_root() {
    let content = include_str!("../src/precommit_template.sh");
    assert!(
        content.contains("git rev-parse --show-toplevel"),
        "Template should get the project root"
    );
}

#[test]
fn test_precommit_template_cd_to_project_root() {
    let content = include_str!("../src/precommit_template.sh");
    assert!(
        content.contains("cd \"$PROJECT_ROOT\""),
        "Template should change to project root before running checks"
    );
}

#[test]
fn test_precommit_provides_help_message() {
    let content = include_str!("../src/precommit_template.sh");
    assert!(
        content.contains("sentinel pro audit") || content.contains("sentinel pro check"),
        "Template should provide helpful debugging instructions"
    );
}

#[test]
fn test_precommit_is_deterministic() {
    // The template content should be consistent
    let content1 = include_str!("../src/precommit_template.sh");
    let content2 = include_str!("../src/precommit_template.sh");
    assert_eq!(content1, content2, "Template should be deterministic");
}
