//! Pre-commit hook installation and management

use colored::Colorize;
use std::fs;
use std::path::Path;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

/// Pre-commit hook template (embedded in binary)
const PRECOMMIT_TEMPLATE: &str = include_str!("../precommit_template.sh");

pub enum PreCommitAction {
    Install,
    Uninstall,
    Status,
}

/// Handle pre-commit hook operations
pub fn handle_precommit_command(project_root: &Path, action: PreCommitAction) {
    let git_dir = project_root.join(".git");
    let hooks_dir = git_dir.join("hooks");
    let hook_file = hooks_dir.join("pre-commit");

    // Check if this is a git repository
    if !git_dir.exists() {
        eprintln!(
            "{}",
            "Error: Not a git repository. Initialize git first with 'git init'".red()
        );
        std::process::exit(1);
    }

    match action {
        PreCommitAction::Install => {
            install_precommit_hook(project_root, &hook_file, &hooks_dir)
        }
        PreCommitAction::Uninstall => {
            uninstall_precommit_hook(&hook_file)
        }
        PreCommitAction::Status => {
            show_precommit_status(&hook_file)
        }
    }
}

fn install_precommit_hook(_project_root: &Path, hook_file: &Path, hooks_dir: &Path) {
    // Create hooks directory if it doesn't exist
    if !hooks_dir.exists() {
        if let Err(e) = fs::create_dir_all(hooks_dir) {
            eprintln!("{}", format!("Error creating hooks directory: {}", e).red());
            std::process::exit(1);
        }
    }

    // Check if hook already exists
    if hook_file.exists() {
        println!(
            "{}",
            "Pre-commit hook already exists. Backing up existing hook...".yellow()
        );

        let backup_file = format!("{}.backup", hook_file.display());
        if let Err(e) = fs::copy(hook_file, &backup_file) {
            eprintln!(
                "{}",
                format!("Error backing up existing hook: {}", e).red()
            );
            std::process::exit(1);
        }
        println!("  Backup saved to: {}", backup_file.cyan());
    }

    // Write the pre-commit hook
    if let Err(e) = fs::write(hook_file, PRECOMMIT_TEMPLATE) {
        eprintln!("{}", format!("Error writing pre-commit hook: {}", e).red());
        std::process::exit(1);
    }

    // Make the hook executable (Unix-like systems)
    #[cfg(unix)]
    {
        let mut perms = fs::metadata(hook_file)
            .expect("Failed to read hook metadata")
            .permissions();
        perms.set_mode(0o755);
        if let Err(e) = fs::set_permissions(hook_file, perms) {
            eprintln!("{}", format!("Error making hook executable: {}", e).red());
            std::process::exit(1);
        }
    }

    println!("{}", "✅ Pre-commit hook installed successfully!".green());
    println!();
    println!("The following checks will run before each commit:");
    println!("  • Static analysis on staged files");
    println!("  • Pattern matching for common issues");
    println!("  • File format validation");
    println!();
    println!("To bypass the hook, use: {}", "git commit --no-verify".cyan());
}

fn uninstall_precommit_hook(hook_file: &Path) {
    if !hook_file.exists() {
        println!(
            "{}",
            "Pre-commit hook is not installed.".yellow()
        );
        return;
    }

    // Check if the hook was installed by Sentinel
    if let Ok(content) = fs::read_to_string(hook_file) {
        if !content.contains("Pre-commit hook generated by Sentinel Pro") {
            eprintln!(
                "{}",
                "Warning: This pre-commit hook was not installed by Sentinel.".yellow()
            );
            eprintln!("Refusing to uninstall to avoid removing custom hooks.");
            std::process::exit(1);
        }
    }

    // Create a backup before removing
    let backup_file = format!("{}.backup", hook_file.display());
    if let Err(e) = fs::copy(hook_file, &backup_file) {
        eprintln!("{}", format!("Error creating backup: {}", e).red());
        std::process::exit(1);
    }

    // Remove the hook file
    if let Err(e) = fs::remove_file(hook_file) {
        eprintln!("{}", format!("Error removing pre-commit hook: {}", e).red());
        std::process::exit(1);
    }

    println!("{}", "✅ Pre-commit hook uninstalled successfully!".green());
    println!("  Backup saved to: {}", backup_file.cyan());
}

fn show_precommit_status(hook_file: &Path) {
    if !hook_file.exists() {
        println!(
            "{}",
            "Pre-commit hook: {} (not installed)".yellow(),
        );
        return;
    }

    // Check if it was installed by Sentinel
    if let Ok(content) = fs::read_to_string(hook_file) {
        if content.contains("Pre-commit hook generated by Sentinel Pro") {
            println!("{}", "Pre-commit hook: ✅ Installed".green());

            // Check if executable
            if let Ok(_metadata) = fs::metadata(hook_file) {
                #[cfg(unix)]
                {
                    use std::os::unix::fs::PermissionsExt;
                    let perms = _metadata.permissions();
                    let mode = perms.mode();
                    if mode & 0o111 != 0 {
                        println!("  Status: Executable");
                    } else {
                        println!("  Status: {} (not executable)", "⚠".yellow());
                    }
                }
            }
        } else {
            println!("{}", "Pre-commit hook: ⚠️  Custom hook (not by Sentinel)".yellow());
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_precommit_template_contains_sentinel_marker() {
        assert!(
            PRECOMMIT_TEMPLATE.contains("Pre-commit hook generated by Sentinel Pro"),
            "Template should contain Sentinel marker"
        );
    }

    #[test]
    fn test_precommit_template_is_valid_bash() {
        assert!(
            PRECOMMIT_TEMPLATE.starts_with("#!/bin/bash"),
            "Template should start with bash shebang"
        );
    }

    #[test]
    fn test_precommit_template_has_checks() {
        assert!(
            PRECOMMIT_TEMPLATE.contains("Running Sentinel pre-commit checks"),
            "Template should mention running checks"
        );
    }
}
