#!/bin/bash
# Pre-commit hook generated by Sentinel Pro
# This hook runs Sentinel checks on staged files before committing

set -e

# Get the list of staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

# Exit early if no files are staged
if [ -z "$STAGED_FILES" ]; then
    exit 0
fi

echo "🔍 Running Sentinel pre-commit checks..."

# Determine the project root
PROJECT_ROOT=$(git rev-parse --show-toplevel)
cd "$PROJECT_ROOT"

# Run Sentinel check on staged files
FAILED=0
for FILE in $STAGED_FILES; do
    # Only check code files (skip vendor, build dirs, etc.)
    if [[ "$FILE" =~ \.(ts|tsx|js|jsx|rs|java|go|py)$ ]]; then
        echo "  Checking: $FILE"

        # Run sentinel check (adjust based on your implementation)
        if ! sentinel pro check "$FILE" --format=json >/dev/null 2>&1; then
            echo "    ❌ Sentinel check failed for $FILE"
            FAILED=1
        else
            echo "    ✅ OK"
        fi
    fi
done

if [ $FAILED -eq 1 ]; then
    echo ""
    echo "❌ Pre-commit checks failed. Fix issues and try again."
    echo "   Run 'sentinel pro audit $FILE' to see details."
    echo ""
    echo "   To bypass this check (not recommended): git commit --no-verify"
    exit 1
fi

echo ""
echo "✅ Pre-commit checks passed!"
exit 0
